import localFont from "next/font/local";
import "./styles/globals.css";
import "./styles/vendors/menu.css"
import {SpeedInsights} from "@vercel/speed-insights/next";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "XCon Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <SpeedInsights/>
        {children}
      </body>
    </html>
  );
}
